TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(RFM69_SUPPORT)_SRC += hardware/radio/rfm69/rfm69.c
$(RFM69_SUPPORT)_ECMD_SRC += hardware/radio/rfm69/rfm69_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
